config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  get '/items/search' => 'items#search'
  get '/items/random_page' => 'items#random_page'
  get '/items/random' => 'items#random'
  get '/users/new_select' => 'users#new_select'
  post 'users/pay' => 'users#pay'
  post 'users/card_delete' => 'users#card_delete'
  resources :items do
    member do
      get 'purchase' => 'items#purchase'
      patch "purchase_patch" => 'items#purchace_patch'
    end
  end
  resources :users,only: [:show,:create] do
    member do
      get 'logout_page' => 'users#logout_page'
      get 'profile' => 'users#profile'
      get 'identification' => 'users#identification'
      get 'card' => 'users#card'
      get 'card_create' => 'users#card_create'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :exhibitors
  has_many :buyers
  has_many :credits

  devise :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # callback for facebook
  def facebook
    callback_for(:facebook)
  end
  
  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def create
    credit = Credit.create(credit_params)
    redirect_to("/")
  end

  def show
    @user = User.find(current_user.id)
  end

  def logout_page
    @user = User.find(params[:id])
  end

  def new_select
  end

  def profile
    @user = User.find(params[:id])
  end

  def identification
    @user = User.find(params[:id])
  end

  def card
    @user = User.find(params[:id])
    card = Credit.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "card_create" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def card_create
    @user = User.find(current_user.id)
  end

  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "card_create"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token']
      )
      @card = Credit.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to "/users/card"
      else
        redirect_to action: "pay"
      end
    end
  end

  def card_delete
    card = Credit.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to "/users/card"
  end

end

app/views/users/_mypage.html.haml
.mypage
  .mypage__lists
    .mypage__list
      .mypage__title マイページ
      %ul
        = link_to "", alt: "" do
          %li
            お知らせ
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            やることリスト
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            いいね!一覧
            %i.fas.fa-chevron-right
        = link_to new_item_path, alt: "" do
          %li
            出品する
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            出品した商品-出品
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            出品した商品-取引中
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            出品した商品-売却済み
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            購入した商品-取引中
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            購入した商品-過去の取引
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            ニュース一覧
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            評価一覧
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            ガイド
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            お問い合わせ
            %i.fas.fa-chevron-right
    .mypage__list
      .mypage__title
        %p メルペイ
      %ul
        = link_to "", alt: "" do
          %li
            売上・振込申請
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            ポイント
            %i.fas.fa-chevron-right
    .mypage__list
      .mypage__title
        %p 設定
      %ul
        = link_to profile_user_path(id: @user.id), alt: "" do
          %li
            プロフィール
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            発送元・お届け先住所変更
            %i.fas.fa-chevron-right
        = link_to card_user_path(id: current_user.id), alt: "" do
          %li
            支払い方法
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            メール/パスワード
            %i.fas.fa-chevron-right
        = link_to identification_user_path(id: @user.id), alt: "" do
          %li
            本人情報
            %i.fas.fa-chevron-right
        = link_to "", alt: "" do
          %li
            電話番号の確認
            %i.fas.fa-chevron-right
        = link_to logout_page_user_path(id: @user.id), alt: "" do
          %li
            ログアウト
            %i.fas.fa-chevron-right

app/views/users/card.html.haml
.home
  = render partial: "items/header"

.users
  .card
    %main
      .title
        %p 支払い方法
      .card-index
        %p クレジットカード一覧
        .add-card
          = link_to("クレジットカードを追加する", card_create_user_path(id: current_user.id), class: "add-card-btn")
      .payment-method
        = link_to("支払い方法について", "", class: "payment-method-btn")

      %label 登録クレジットカード情報
      %br
      = credit_show
      %br
      = credit_addition
      = form_tag("/users/card_delete", method: :post, id: 'charge-form',  name: "inputForm") do
        %input{ type: "hidden", name: "card_id", value: "" }
        %button 削除する


= render partial: "mypage"
.home
  = render partial: "items/footer"

app/views/users/card_create.html.haml
.home
  = render partial: "items/header"

.users
  .card-create
    %main
      .card-lists
        .title
          %p クレジットカード情報入力
        = form_tag(users_pay_path, method: :post, id: 'charge-form',  name: "inputForm") do
          .card-number
            .card-p
              %p.card-title カード番号 
              %p.hissu 必須
            = text_field_tag "number", "", class: "number input", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            .images
              = image_tag "/assets/credit_1.svg"
              = image_tag "/assets/credit_2.svg"
              = image_tag "/assets/credit_3.svg"
              = image_tag "/assets/credit_4.svg"
              = image_tag "/assets/credit_5.svg"
              = image_tag "/assets/credit_6.svg"
              = image_tag "/assets/credit_7.svg"
            %br
          .card-expiration
            .card-p
              %p.card-title 有効期限
              %p.hissu 必須
            .expiration-select
              %select#exp_month{name: "exp_month", type: "text"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %span 月/
              %select#exp_year{name: "exp_year", type: "text"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %span 年
              %br
          .card-code
            .card-p
              %p.card-title セキュリティコード
              %p.hissu 必須
            = text_field_tag "cvc", "", class: "cvc input", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
            %p.card-back
              = link_to("カード裏面の番号とは?", "", class: "card-back-btn")
          #card_token
          .add-card
            = submit_tag "追加する", id: "token_submit", class: "add-card-btn"

= render partial: "mypage"
.home
  = render partial: "items/footer"

app/views/users/identification.html.haml
.home
  = render partial: "items/header"
  .pan
    %ul
      %li= link_to("メルカリ","/", class: "page")
      %li
        %i.fas.fa-chevron-right
      %li= link_to"マイページ", user_path(@user.id), class: "page"
      %li
        %i.fas.fa-chevron-right
      %li= link_to("本人情報","", class: "current-page")
.users
  .identification
    .identification-title
      %p 本人情報の登録
    .identification-contents
      .identification-content.content-top
        %p お客さまの本人情報をご登録ください。登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        %a{:href => ""}
          本人確認書類のアップロードについて
          %i.fas.fa-chevron-right
      .identification-content
        %p.name-title お名前
        %p= @user.name
      .identification-content
        %p.name-title お名前カナ
        %p= @user.name
      .identification-content
        %p.name-title 生年月日
        %p
      .identification-content
        %p.name-title 郵便番号
        %input{:placeholder => "例) 1234567", :type => "text"}/
      .identification-content
        %p.name-title 都道府県
        %input{:type => "text"}/
      .identification-content
        %p.name-title 市区町村
        %input{:type => "text"}/
      .identification-content
        %p.name-title 番地
        %input{:type => "text"}/
      .identification-content
        %p.name-title 建物名
        %input{:type => "text"}/
      .register
        = link_to("登録する","", class: "register-btn")
      .identification-content
        %a{:href => ""}
          本人情報の登録について
          %i.fas.fa-chevron-right
= render partial: "mypage"
.home
  = render partial: "items/footer"

app/views/users/logout_page.html.haml
.home
  = render partial: "items/header"
  .pan
    %ul
      %li= link_to("メルカリ","/", class: "page")
      %li
        %i.fas.fa-chevron-right
      %li= link_to("マイページ","/users/#{@user.id}", class: "page")
      %li
        %i.fas.fa-chevron-right
      %li= link_to("ログアウト","", class: "current-page")
.mypage
  .center
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout"
= render partial: "mypage"
.home
  = render partial: "items/footer"

app/views/users/new_select.html.haml
.users
  .users-new-select
    = render "layouts/mercari-top"
    %main
      .users-new-select-title
        %p 新規会員登録
      .users-new-select-lists
        .users-new-select-lists-email
          .users-email
            = link_to "メールアドレスで登録", new_user_registration_path, class: 'users-email-btn'
        .users-sns
          .users-sns-link
            .users-sns-link-facebook
              = link_to "Facebookでログイン", "", class: "facebook-btn"
              %br/
          .users-sns-link
            .users-sns-link-google
              = link_to "Googleでログイン", "", class: "google-btn"
    = render "layouts/mercari-bottom"

app/views/users/profile.html.haml
.home
  = render partial: "items/header"
  .pan
    %ul
      %li= link_to("メルカリ", root_path, class: "page")
      %li
        %i.fas.fa-chevron-right
      %li= link_to("マイページ", user_path(@user.id), class: "page")
      %li
        %i.fas.fa-chevron-right
      %li= link_to("プロフィール","", class: "current-page")
.users
  .profile
    .profile-top
      %p プロフィール
      .relative
        = image_tag "https://4.bp.blogspot.com/-Zy9QmWxqcqU/WpJjYRSrhKI/AAAAAAAABHw/HWN7vKwTUNEtCdgeYdAbixlELRvI_RdyQCLcBGAs/s1600/01s11.png", alt: ""
        .absolute
          %i.far.fa-user.fa-3x
          %input{:type => "text", :value => "#{@user.name}"}/
    .profile-bottom
      .textarea
        %input{:placeholder => "例) こんにちは", :type => "textarea"}/
      .profile-change
        = link_to("変更する","", class: "change-btn")
= render partial: "mypage"
.home
  = render partial: "items/footer"

app/views/users/show.html.haml
.home
  = render partial: "items/header"
  .pan
    %ul
      %li
        = link_to("メルカリ", root_path, class: "page")
      %li
        %i.fas.fa-chevron-right
      %li
        = link_to("マイページ", "", class: "current-page")
.mypage
  .mypage__user
    = image_tag "/assets/シマシマ.png", alt: ""
    .mypage__user__information
      .user__icon
        %i.far.fa-user.fa-3x
      .user__name= current_user.name
= render partial: "mypage"
.home
  = render partial: "items/footer"