config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  get '/items/search' => 'items#search'
  get '/items/random_page' => 'items#random_page'
  get '/items/random' => 'items#random'
  get '/users/new_select' => 'users#new_select'
  post 'users/pay' => 'users#pay'
  post 'users/card_delete' => 'users#card_delete'
  resources :items do
    member do
      get 'purchase' => 'items#purchase'
      patch "purchase_patch" => 'items#purchace_patch'
    end
  end
  resources :users,only: [:show,:create] do
    member do
      get 'logout_page' => 'users#logout_page'
      get 'profile' => 'users#profile'
      get 'identification' => 'users#identification'
      get 'card' => 'users#card'
      get 'card_create' => 'users#card_create'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :bland
  belongs_to :exhibitor
  belongs_to :buyer

  mount_uploader :image, ImageUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:search,:show,:random_page]

  def index
    @items = Item.all.order(created_at: :desc)
  end

  def new
    @item = Item.new
    @category = Category.new
    @bland = Bland.new
  end

  def create
    category = Category.create(category_params)
    bland = Bland.create(bland_params)
    exhibitor = Exhibitor.create(exhibitor_params)
    unless params[:item][:image] == nil ||  params[:item][:name] == nil || params[:item][:price] == nil || params[:item][:explain] == nil || params[:item][:status] == "---" || params[:item][:shipping_which] == "---" || params[:item][:shipping_region] == "---" || params[:item][:shipping_method] == "---" || params[:item][:shipping_day] == "---"
      item_params = params.require(:item).permit(:image, :name, :explain, :status, :price, :shipping_which, :shipping_region, :shipping_method, :shipping_day).merge(exhibitor_id: exhibitor.id, category_id: category.id, bland_id: bland.id, buyer_id: 0)
      item = Item.create(item_params)
      redirect_to(root_path)
    else
      flash[:notice] = '値を正しく入力してください'
      redirect_to(new_item_path)
    end
  end

  def show
    @item = Item.find(params[:id])
    @user = @item.exhibitor.user
    @category = @item.category
    @bland = @item.bland
    
    @number = params[:number]
  end

  def edit
    @item = Item.find(params[:id])
    @category = Category.find(@item.category.id)
    @bland = Bland.find(@item.bland.id)
  end

  def update
    item = Item.find(params[:id])
    category = Category.find(item.category.id)
    bland = Bland.find(item.bland.id)
    user = item.exhibitor.user
    item_params = params.require(:item).permit(:image, :name, :explain, :status, :price, :shipping_which, :shipping_region, :shipping_method, :shipping_day)
    if user.id == current_user.id
      item.update(item_params)
    end
    redirect_to(root_path)
  end

  def destroy
    item = Item.find(params[:id])
    user = item.exhibitor.user
    if user.id == current_user.id
      item.destroy
    end
    redirect_to(root_path)
  end

  def purchase
    @item = Item.find(params[:id])
    @user = @item.exhibitor.user

    card = Credit.where(user_id: current_user.id).first
    if card.blank?
      redirect_to controller: "card", action: "card_create"
    else
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def purchace_patch
    @item = Item.find(params[:id])
    Buyer.create(user_id: current_user.id)
    @item.buyer_id = current_user.id
    @item.save

    card = Credit.where(user_id: current_user.id).first
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if Payjp::Charge.create(
    amount: @item.price,
    customer: card.customer_id,
    currency: 'jpy',
    )
      redirect_to(root_path)
    else
      flash[:notice] = '購入できませんでした'
    end

  end

  def search
    @items = Item.all.order(created_at: :desc)
  end

  def random_page
  end

  def random
    @rand = rand(1..100)
    id = Item.where(buyer_id: 0).ids
    number = Item.where(buyer_id: 0).count
    @random = id[rand(number)]
  end

  private

  def category_params
    params.require(:category).permit(:category_large, :category_medium, :category_small, :category_size)
  end

  def bland_params
    params.require(:bland).permit(:bland_name)
  end

  def exhibitor_params
    params.require(:item).permit().merge(user_id: current_user.id)
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_category.html.haml
:javascript
  $(function(){
    function mediumbuildHTML(id){
      if(id == 1){
        // レディース
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","トップス","ジャケット/アウター","パンツ","スカート","ワンピース","靴","ルームウェア","レッグウェア","帽子","バッグ","アクセサリー","ヘアアクセサリー","小物","時計","ウィッグ/エクステ","浴衣/水着","スーツ/フォーマル/ドレス","マタニティ","その他"] , class: "select", id: "select_btn_medium"}</div> `
      } else if(id == 2){
        // メンズ
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","トップス","ジャケット/アウター","パンツ","靴","レッグウェア","アンダーウェア","帽子","バッグ","スーツ","アクセサリー","小物","時計","水着","その他"] , class: "select", id: "select_btn_medium"}</div> `
      } else if(id == 3){
        // ベビー・キッズ
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","ベビー服(女の子用)~95cm","ベビー服(男の子用)~95cm","ベビー服(男女兼用)~95cm","キッズ服(女の子用)100cm~","キッズ服(男の子用)100cm~","キッズ服(男女兼用)100cm~","キッズ靴","子供用ファッション小物","オムツ/トイレ/バス","外出/移動用品","授乳/食事","ベビー家具/寝具/室内用品","おもちゃ","行事/記念品","その他"] , class: "select", id: "select_btn_medium"}</div> `
      } else if(id == 4){
        // インテリア・住まい・小物
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","キッチン/食器","ベッド/マットレス","ソファ/ソファベッド","椅子/チェア","机/テーブル","収納家具","ラグ/カーペット/マット","カーテン/ブラインド","ライト/照明","寝具","インテリア小物","季節/年中行事","その他"] , class: "select", id: "select_btn_medium"}</div> `
      } else if(id == 5){
        // 本・音楽・ゲーム
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","本","漫画","雑誌","CD","DVD/ブルーレイ","レコード","テレビゲーム"] , class: "select", id: "select_btn_medium"}</div> `
      } else if(id == 6){
        // おもちゃ・ホビー・グッズ
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","おもちゃ","タレントグッズ","コミック/アニメグッズ","トレーディングカード","フィギュア","楽器/器材","コレクション","ミリタリー","美術品","アート用品","その他"] , class: "select", id: "select_btn_medium"}</div> `
      } else if(id == 7){
        // コスメ・香水・美容
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","ベースメイク","メイクアップ","ネイルケア","香水","スキンケア/基礎化粧品","ヘアケア","ボディケア","オーラルケア","リラクゼーション","ダイエット","その他"] , class: "select", id: "select_btn_medium"}</div> `
      } else if(id == 8){
        // 家電・スマホ・カメラ
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","スマートフォン/携帯電話","スマホアクセサリー","PC/タブレット","カメラ","テレビ/映像機器","オーディオ機器","美容/健康","冷暖房/空調","生活家電","その他"] , class: "select", id: "select_btn_medium"}</div> `
      } else if(id == 9){
        // スポーツ・レジャー
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","ゴルフ","フィッシング","自転車","トレーニング/エクササイズ","野球","サッカー/フットサル","テニス","スノーボード","スキー","その他スポーツ","アウトドア","その他"] , class: "select", id: "select_btn_medium"}</div> `
      } else if(id == 10){
        // ハンドメイド
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","アクセサリー(女性用)","ファッション/小物","アクセサリー/時計","日用品/インテリア","趣味/おもちゃ","キッズ/ベビー","素材/材料","二次創作物","その他"] , class: "select", id: "select_btn_medium"}</div> `
      } else if(id == 11){
        // チケット
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","音楽","スポーツ","演劇/芸能","イベント","映画","施設利用券","優待券/割引券","その他"] , class: "select", id: "select_btn_medium"}</div> `
      } else if(id == 12){
        // 自転車・オートバイ
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","自動車本体","自動車タイヤ/ホイール","自動車パーツ","自動車アクセサリー","オートバイ車体","オートバイパーツ","オートバイアクセサリー","その他"] , class: "select", id: "select_btn_medium"}</div> `
      } else {
        // その他
        var html = `<div id="category_medium">#{c.select :category_medium, ["---","まとめ売り","ペット用品","食品","飲料/酒","日用品/生活雑貨/旅行","アンティーク/コレクション","文房具/事務用品","事務/店舗用品","その他"] , class: "select", id: "select_btn_medium"}</div> `
      }
      return html;
    }
    function smallbuildHTML(idl,idm){
      // レディース
      if(idl == 1 && idm == 1){
        var html = `#{c.select :category_small, ["---","Tシャツ/カットソー(半袖/袖なし)","Tシャツ/カットソー(七分/長袖)","シャツ/ブラウス(半袖/袖なし)","シャツ/ブラウス(七分/長袖)","ポロシャツ","キャミソール","タンクトップ","ホルターネック","ニット/セーター","チュニック","カーディガン/ボレロ","アンサンブル","ベスト/ジレ","パーカー","トレーナー/スウェット","ペアトップ/チューブトップ","ジャージ","その他"], class: "select"}`
      } else if(idl == 1 && idm == 2) {
        var html = `#{c.select :category_small, ["---","テーラードジャケット","ノーカラージャケット","Gジャン/デニムジャケット","レザージャケット","ダウンジャケット","ライダースジャケット","ミリタリージャケット","ダウンベスト","ジャンパー/ブルゾン","ポンチョ","ロングコート","トレンチコート","ダッフルコート","ピーコート","チェスターコート","モッズコート","スタジャン毛皮/ファーコート","スプリングコート","スカジャン","その他"], class: "select"}`
      } else if(idl == 1 && idm == 3) {
        var html = `#{c.select :category_small, ["---","デニム/ジーンズ","ショートパンツ","カジュアルパンツ","ハーフパンツ","チノパン","ワークパンツ/カーゴパンツ","クロップドパンツ","サロペット/オーバーオール","オールインワン","サルエルパンツ","ガウチョパンツ","その他"], class: "select"}`
      } else if(idl == 1 && idm == 4) {
        var html = `#{c.select :category_small, ["---","ミニスカート","ひざ丈スカート","ロングスカート","キュロット","その他"], class: "select"}`
      } else if(idl == 1 && idm == 5) {
        var html = `#{c.select :category_small, ["---","ミニワンピース","ひざ丈ワンピース","ロングワンピース","その他"], class: "select"}`
      } else if(idl == 1 && idm == 6) {
        var html = `#{c.select :category_small, ["---","ハイヒール/パンプス","ブーツ","サンダル","スニーカー","ミュール","モカシン","ローファー/革靴","フラットシューズ/バレエシューズ","長靴/レインシューズ","その他"], class: "select"}`
      } else if(idl == 1 && idm == 7) {
        var html = `#{c.select :category_small, ["---","パジャマ","ルームウェア"], class: "select"}`
      } else if(idl == 1 && idm == 8) {
        var html = `#{c.select :category_small, ["---","ソックス","スパッツ/レギンス","ストッキング/タイツ","レッグウォーマー","その他"], class: "select"}`
      } else if(idl == 1 && idm == 9) {
        var html = `#{c.select :category_small, ["---","ニットキャップ/ビーニー","ハット","ハンチング/ベレー帽","キャップ","キャスケット","麦わら帽子","その他"], class: "select"}`
      } else if(idl == 1 && idm == 10) {
        var html = `#{c.select :category_small, ["---","ハンドバッグ","トートバッグ","エコバッグ","リュック/バックパック","ボストンバッグ","スポーツバッグ","ショルダーバッグ","クラッチバッグ","ポーチ/バニティ","ボディバッグ/ウェストバッグ","マザーズバッグ","メッセンジャーバッグ","ビジネスバッグ","旅行用バッグ/キャリーバッグ","ショップ袋","和装用バッグ","かごバッグ","その他"], class: "select"}`
      } else if(idl == 1 && idm == 11) {
        var html = `#{c.select :category_small, ["---","ネックレス","ブレスレット","バングル/リストバンド","リングピアス(片耳用)","ピアス(両耳用)","イヤリング","アンクレットブローチ/コサージュ","チャーム","その他"], class: "select"}`
      } else if(idl == 1 && idm == 12) {
        var html = `#{c.select :category_small, ["---","ヘアゴム/シュシュ","ヘアバンド/カチューシャ","ヘアピン","その他"], class: "select"}`
      } else if(idl == 1 && idm == 13) {
        var html = `#{c.select :category_small, ["---","長財布","折り財布","コインケース/小銭入れ","名刺入れ/定期入れ","キーケース","キーホルダー","手袋/アームカバー","ハンカチ","ベルト","マフラー/ショール","ストール/スヌード","バンダナ/スカーフ","ネックウォーマー","サスペンダー","サングラス/メガネ","モバイルケース/カバー","手帳","イヤマフラー","傘","レインコート/ポンチョ","ミラー","タバコグッズ","その他"], class: "select"}`
      } else if(idl == 1 && idm == 14) {
        var html = `#{c.select :category_small, ["---","腕時計(アナログ)","腕時計(デジタル)","ラバーベルト","レザーベルト","金属ベルト","その他"], class: "select"}`
      } else if(idl == 1 && idm == 15) {
        var html = `#{c.select :category_small, ["---","前髪ウィッグ","ロングストレート","ロングカール","ショートストレート","ショートカール","その他"], class: "select"}`
      } else if(idl == 1 && idm == 16) {
        var html = `#{c.select :category_small, ["---","浴衣","着物","振袖","長襦袢/半襦袢","水着セパレート","水着ワンピース","水着スポーツ用","その他"], class: "select"}`
      } else if(idl == 1 && idm == 17) {
        var html = `#{c.select :category_small, ["---","スカートスーツ上下","パンツスーツ上下","ドレス","パーティーバッグ","シューズ","ウェディング","その他"], class: "select"}`
      } else if(idl == 1 && idm == 18) {
        var html = `#{c.select :category_small, ["---","トップス","アウター","インナー","ワンピース","パンツ/スパッツ","スカート","パジャマ","授乳服","その他"], class: "select"}`
      // メンズ
      } else if(idl == 2 && idm == 1) {
        var html = `#{c.select :category_small, ["---","Tシャツ/カットソー(半袖/袖なし)","Tシャツ/カットソー(七分/長袖)","シャツ","ポロシャツ","タンクトップ","ニット/セーター","パーカー","カーディガン","スウェット","ジャージ","ベスト","その他"], class: "select"}`
      } else if(idl == 2 && idm == 2) {
        var html = `#{c.select :category_small, ["---","テーラードジャケット","ノーカラージャケット","Gジャン/デニムジャケット","レザージャケット","ダウンジャケット","ライダースジャケット","ミリタリージャケット","ナイロンジャケット","フライトジャケット","ダッフルコート","ピーコート","ステンカラーコート","トレンチコート","モッズコート","チェスターコート","スタジャン","スカジャン","ブルゾン","マウンテンパーカー","ダウンベスト","ポンチョ","カバーオール","その他"], class: "select"}`
      } else if(idl == 2 && idm == 3) {
        var html = `#{c.select :category_small, ["---","デニム/ジーンズ","ワークパンツ/カーゴパンツ","スラックス","チノパン","ショートパンツ","ペインターパンツ","サルエルパンツ","オーバーオール","その他"], class: "select"}`
      } else if(idl == 2 && idm == 4) {
        var html = `#{c.select :category_small, [""], class: "select"}`
      } else if(idl == 2 && idm == 5) {
        var html = `#{c.select :category_small, [""], class: "select"}`
      } else if(idl == 2 && idm == 6) {
        var html = `#{c.select :category_small, [""], class: "select"}`
      } else if(idl == 2 && idm == 7) {
        var html = `#{c.select :category_small, [""], class: "select"}`
      } else if(idl == 2 && idm == 8) {
        var html = `#{c.select :category_small, [""], class: "select"}`
      } else if(idl == 2 && idm == 9) {
        var html = `#{c.select :category_small, [""], class: "select"}`
      } else if(idl == 2 && idm == 10) {
        var html = `#{c.select :category_small, [""], class: "select"}`
      } else if(idl == 2 && idm == 11) {
        var html = `#{c.select :category_small, [""], class: "select"}`
      } else if(idl == 2 && idm == 12) {
        var html = `#{c.select :category_small, [""], class: "select"}`
      } else if(idl == 2 && idm == 13) {
        var html = `#{c.select :category_small, [""], class: "select"}`
      } else if(idl == 2 && idm == 14) {
        var html = `#{c.select :category_small, [""], class: "select"}`
      }
      return html;
    }
    
    //changeした時削除しないといけない

    $('#category_large').on('change',function(){
      $('#category_category_medium').remove();
      $('#category_category_small').remove();
      $('#main-detail').css({'height':'420'})
      var indexId = getIndexNo('category_category_large');
      var html = mediumbuildHTML(indexId);
      $('#add_select').append(html);
    })
    $(document).on('change','#category_medium',function(){
      $('#category_category_small').remove();
      $('#main-detail').css({'height':'480'})
      var indexId_large = getIndexNo('category_category_large');
      var indexId_medium = getIndexNo('category_category_medium');
      var html = smallbuildHTML(indexId_large,indexId_medium);
      $('#add_select').append(html);
    })
  });

app/views/items/_footer.html.haml
%footer
  .footer-top
    .footer-lists
      %p.footer-head メルカリについて
      .footer-list
        %a{:href => ""} 会社概要（運営会社）
        %a{:href => ""} 採用情報
        %a{:href => ""} プレスリリース
        %a{:href => ""} 公式ブログ
        %a{:href => ""} メルカリロゴ利用ガイドライン
    .footer-lists
      %p.footer-head ヘルプ&amp;ガイド
      .footer-list
        %a{:href => ""} メルカリガイド
        %a{:href => ""} らくらくメルカリ便
        %a{:href => ""} ゆうゆうメルカリ便
        %a{:href => ""} 大型メルカリ便
        %a{:href => ""} 車体取引ガイド
        %a{:href => ""} メルカリあんしん・あんぜん宣言！
        %a{:href => ""} 偽ブランド品撲滅への取り組み
    .footer-lists
      %p.footer-head プライバシーと利用規約
      .footer-list
        .footer-list-privacy
          .footer-list-left
            %a{:href => ""} プライバシーポリシー
            %a{:href => ""} メルカリ利用規約
            %a{:href => ""} あんしんスマホサポート制度に関する利用特約
            %a{:href => ""} コンプライアンスポリシー
          .footer-list-right
            %a{:href => ""} 個人データの安全管理に係る基本方針
            %a{:href => ""} 特定商取引に関する表記
            %a{:href => ""} 資金決済法に基づく表示
            %a{:href => ""} 法令遵守と犯罪防止のために
            %a{:href => ""} 返品・返金ポリシー
    .footer-lists
      %p.footer-head 国
      .footer-list
        %a{:href => ""} 日本
        %a{:href => ""} United States
  .footer-bottom
    %a{:href => "/"}
      %img{:alt => "", :src => "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?376951604"}/
    %p © 2019 Mercari

app/views/items/_header.html.haml
%header
  .header-top
    .header-top-title
      %a{:href => "/"}
        %img{:alt => "", :src => "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?613028459"}/
    - if user_signed_in?
      .header-top-icon
        %i.user-image
        %i.far.fa-bell.fa-lg
        %i.fas.fa-check.fa-lg
        %a{:href => "/users/#{current_user.id}"}
          %i.fas.fa-user.fa-lg
    - else
      %div
        .header-top-icon
          = link_to "新規登録", "/users/new_select", class: 'new'
          = link_to "ログイン", new_user_session_path, class: 'login'
  .header-middle
    %input{:placeholder => "何をお探しですか？", :type => "text"}/
    %a{:href => "/items/search"}
      %i.fas.fa-search
  .header-bottom
    .header-bottom-right
      #search-category.header-bottom-search
        %i.fas.fa-list
        %ul.menu
          %li.menu__multi
            %a.header-bottom-search-type.init-bottom{:href => "#"} カテゴリーから探す
            %ul.menu__second-level
              / レディース　第一階層
              %li
                %a.init-right{:href => "#"} レディース
                %ul.menu__third-level
                  / 第二階層
                  %li
                    %a.init-right{:href => "#"} トップス
                    %ul.menu__fourth-level
                      / 第三階層
                      %li
                        %a{:href => "#"} Tシャツ
                      %li
                        %a{:href => "#"} カットソー
                      %li
                        %a{:href => "#"} ネックレス
                  %li
                    %a{:href => "#"} ジャケット
                  %li
                    %a{:href => "#"} パンツ
              %li
                %a.init-right{:href => "#"} メンズ
              %li
                %a.init-right{:href => "#"} ベビー・キッズ
              %li
                %a.init-right{:href => "#"} インテリア・住まい・小物
              %li
                %a.init-right{:href => "#"} 本・音楽・ゲーム
              %li
                %a.init-right{:href => "#"} おもちゃ・ホビー・グッズ
              %li
                %a.init-right{:href => "#"} コスメ・香水・美容
              %li
                %a.init-right{:href => "#"} 家電・スマホ・カメラ
              %li
                %a.init-right{:href => "#"} スポーツ・レジャー
              %li
                %a.init-right{:href => "#"} ハンドメイド
              %li
                %a.init-right{:href => "#"} チケット
              %li
                %a.init-right{:href => "#"} 自転車・オートバイ
              %li
                %a.init-right{:href => "#"} その他
    .header-bottom-left
      .header-bottom-search
        %i.fas.fa-tags
        .header-bottom-search-type ブランドから探す

app/views/items/_item-array.html.haml
.pickup-contents
  = link_to("#{type}新着アイテム","#", class: "pickup-type")
  %br/
  .pickup-content
    - @items.each do |item|
      - if item.category.category_large == "#{type}"
        = link_to(item_path(id: item.id), class: "link") do
          .relative
            = image_tag "#{item.image}", alt: ""
            - if item.buyer_id != 0
              %p.sold SOLD
          .item-detail
            %p.item-name= item.name
            .item-price
              %p.item-price-sum
                ¥#{item.price}
              %p.item-price-tax (税込)

app/views/items/random.html.haml
.random
  - if @rand == 1
    %p 割引ガチャガチャの結果『大当たり』が出ました!!!
    - number = 1
    .random-link
      = link_to("商品ガチャガチャへ!",item_path(id: @random, number: number), class: "link")
  - elsif @rand == 2 || @rand == 3 || @rand == 4 || @rand == 5 || @rand == 6 || @rand == 7 || @rand == 8 || @rand == 9 || @rand == 10 || @rand == 11 || @rand == 12 || @rand == 13 || @rand == 14 || @rand == 15 || @rand == 16 || @rand == 17 || @rand == 18 || @rand == 19 || @rand == 20 || @rand == 21
    %p 割引ガチャガチャの結果『あたり』が出ました!!
    - number = 2
    .random-link
      = link_to("商品ガチャガチャへ!",item_path(id: @random, number: number), class: "link")
  - else
    %p 割引ガチャガチャの結果『ふつー』が出ました!
    - number = 3
    .random-link
      = link_to("商品ガチャガチャへ!",item_path(id: @random, number: number), class: "link")

app/views/items/random_page.html.haml
.home
  = render partial: "header"
.random-page
  %main
    .main-title
      %p メルカリガチャガチャ
    .main-content
      .main-left
        = image_tag "/assets/iOS_の画像_(5).png", alt: ""
      .main-right
        .main-right-100
          %p 100ポイントで1回回せます
        .main-right-explain
          %p.overview ＜概要＞
          %p.text ランダムで選ばれる1つの商品を、ガチャガチャの結果に応じた割引価格で購入できます！
        .main-right-discount
          %p 『大当たり』→ 全額無料
          %p 『あたり』→ 2割引
          %p 『ふつー』→ 1割引
        .random-page-btn
          = link_to("100Pを使ってガチャガチャを引く!", items_random_path, class: "random-btn", data: { confirm: "ガチャガチャを回しますか？" })
.home
  = render partial: "footer"

app/views/items/show.html.haml
%body
  .home
    = render partial: "header"
    .pan
      %ul
        %li= link_to("メルカリ",root_path, class: "page")
        %li
          %i.fas.fa-chevron-right
        %li= link_to("#{@item.name}", items_search_path, class: "current-page")
  .item-show
    .random-result
      - if @number == "1"
        %p.item-random
          商品ガチャガチャの結果『#{@item.name}』が出ました!
        %p 割引ガチャガチャの結果『大当たり』が出たので商品が無料になります
      - elsif @number == "2"
        %p.item-random
          商品ガチャガチャの結果『#{@item.name}』が出ました!
        %p 割引ガチャガチャの結果『あたり』が出たので商品が2割引になります
      - elsif @number == "3"
        %p.item-random
          商品ガチャガチャの結果『#{@item.name}』が出ました!
        %p 割引ガチャガチャの結果『ふつー』が出たので商品が1割引になります
    %main
      .main-top
        .item-name
          = @item.name
        .item-detail
          .item-image
            .relative
              %img{:alt => "", :src => "#{@item.image}"}/
              - if @item.buyer_id != 0
                %p.sold SOLD
          .item-table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td
                    = link_to "#{@user.name}", user_path(@user.id)
                %tr
                  %th カテゴリー
                  %td
                    = link_to "#{@category.category_large}", ""
                %tr
                  %th ブランド
                  %td
                    = link_to "#{@bland.bland_name}", ""
                %tr
                  %th 商品のサイズ
                  %td= @category.category_size
                %tr
                  %th 商品の状態
                  %td= @item.status
                %tr
                  %th 配送料の負担
                  %td= @item.shipping_which
                %tr
                  %th 配送の方法
                  %td= @item.shipping_method
                %tr
                  %th 配送元地域
                  %td= @item.shipping_region
                %tr
                  %th 発送日の目安
                  %td= @item.shipping_day
        .item-price
          .item-price-left
            - if @number == "1"
              .random-price
                %p
                  ¥#{@item.price} →
                ¥#{@item.price - @item.price}
            - elsif @number == "2"
              .random-price
                %p
                  ¥#{@item.price} →
                ¥#{@item.price * 80 / 100}
            - elsif @number == "3"
              .random-price
                %p
                  ¥#{@item.price} →
                ¥#{@item.price * 90 / 100}
            - else
              ¥#{@item.price}
          .item-price-right
            .item-tax (税込)
            .item-shipping-which= @item.shipping_which
        - if @item.buyer_id == 0
          .main-btn
            = link_to("購入画面に進む","/items/#{@item.id}/purchase")
        - else
          .main-btn-sold
            %p 売り切れました
        .main-explain
          = @item.explain
      .main-bottom
        - if @user.id == current_user.id
          .item-change
            .item-edit
              = link_to("商品の編集","/items/#{@item.id}/edit", class: "edit-btn")
            %p or
            .item-stop-delete
              .item-stop
                = link_to("出品を一旦停止する","", class: "stop-btn")
              .item-delete
                = link_to("この商品を削除する", "/items/#{@item.id}", method: :delete, :class => "delete-btn")
      .comment
        .comment-title
          %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %input{:type => "textarea"}/
        .item-comment
          = link_to("コメントする","", class: "comment-btn")